[bastion]
# bastion ansible_host=1.2.3.4

[web]
# web1 ansible_host=10.0.1.10
# web2 ansible_host=10.0.1.11

[zabbix]
# zbx ansible_host=10.0.2.10

[elk]
# elk1 ansible_host=10.0.3.10

[all:vars]
# ansible_user=ubuntu
# ansible_ssh_common_args='-o StrictHostKeyChecking=no'
